{
  "hash": "85c256779d9ad552a7bbc2badce92dab",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Wil Rantala\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\n\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(tigris)\nlibrary(tidycensus)\n\n# Load spatial data\n\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_2/data/Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ndistricts <- st_read(\"data/districts.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `U.S._Congressional_Districts_for_Pennsylvania' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_2/data/districts.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 17 features and 8 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51939 ymin: 39.71986 xmax: -74.68956 ymax: 42.26935\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_2/data/hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- hospitals %>%\n  st_transform(st_crs(pa_counties))\n\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |=====================                                                 |  31%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |============================                                          |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- census_tracts %>%\n  st_transform(st_crs(pa_counties))\n\n# Check that all data loaded correctly: Run glimpse() on all the loaded data\n\n\n#checking the reference system -- hospitals and tracts should already match pa_counties' reference system since they've been transformed\n\n### Ran st_crs() on all the loaded data\n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n- How many census tracts?\n- What coordinate reference system is each dataset in?\n\nThere are 223 hospitals, 3445 census tracts, and all of the datasets are in WGS 84 (world geodetic system 1984)\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_demographics <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = c(\n    total_pop = \"B01001_001\",\n    median_income = \"B19013_001\",\n    #To get 65+, I'm summing male and female populations by age ranges 65-85+\n    male_65_66 = \"B01001_020\",\n    male_67_69 = \"B01001_021\",\n    male_70_74 = \"B01001_022\",\n    male_75_79 = \"B01001_023\",\n    male_80_84 = \"B01001_024\",\n    male_85_over = \"B01001_025\",\n    \n    female_65_66 = \"B01001_044\",\n    female_67_69 = \"B01001_045\",\n    female_70_74 = \"B01001_046\",\n    female_75_79 = \"B01001_047\",\n    female_80_84 = \"B01001_048\",\n    female_85_over = \"B01001_049\"\n  ),\n  year = 2024,\n  output = \"wide\"\n)\n\n# Here, I'm mutating to make pop_65_over a single column\n\npa_demographics <- pa_demographics %>%\n  mutate(\n    pop_65_overE = male_65_66E + male_67_69E + male_70_74E +\n      male_75_79E + male_80_84E + male_85_overE + female_65_66E +\n      female_67_69E + female_70_74E + female_75_79E +\n      female_80_84E+ female_85_overE,\n    \n    pop_65_overM = male_65_66M + male_67_69M + male_70_74M +\n      male_75_79M + male_80_84M + male_85_overM + female_65_66M +\n      female_67_69M + female_70_74M + female_75_79M +\n      female_80_84M+ female_85_overM\n  )\n\n# Join to tract boundaries\ncensus_tracts <- census_tracts %>%\n  left_join(pa_demographics, by = \"GEOID\")\n\n#find missing data and median income\nsum(is.na(census_tracts$median_incomeE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 68\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(census_tracts$median_incomeE, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 74844\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n- How many tracts have missing income data?\n- What is the median income across all PA census tracts?\n\nI'm using 2024 5-year ACS data, as it is the most recent available. There are 68 tracts with missing income data. The median income across all PA census tracts (excluding those without income data) is $74,844\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nvulnerable_tracts <- census_tracts %>%\n  mutate(\n    pct_65_over = pop_65_overE / total_popE * 100\n  ) %>%\n  filter(\n    median_incomeE < 35000|\n    pct_65_over > 25 \n  )\n#These are tracts in which the median income is less than 40,000, or the percent of population aged 65 and up is greater than 25%\n```\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n- What elderly population threshold did you choose and why?\n- How many tracts meet your vulnerability criteria?\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\nI chose $35,000 as the threshold as it is a clean number well below the median tract median income of ~75,000. I could have chosen a lower number around 35,000, but that would exclude many households that are vulnerable but not in abject poverty.\n\nI chose 25% as the elderly population threshold as the national average is 17%. Comparatively, a quarter of a tract's population being over the age of 65 is a large proportion.\n\nThere are 847 tracts within both of the vulnerability criteria I set.\n\n24.6% of PA tracts are considered vulnerable by my definition\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n## I transformed to PA State Plane South so we can measure distances in feet to later convert to miles.\n\nvulnerable_tracts_proj <- vulnerable_tracts %>%\n  st_transform(2272)\n\nhosputals_proj <- hospitals %>%\n  st_transform(2272)\n\n\n# Calculate distance from each tract centroid to nearest hospital\n## First I'll get the tract centroids\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\n\n## Now I'll make a matrix that has the distances from centroids to hospitals and select the nearest ones, then convert feet to miles\nhospital_dists <- st_distance(tract_centroids, hosputals_proj)\n\nvulnerable_tracts_proj$nearest_hospital_dist <-\n  apply(hospital_dists, 1, min) / 5280\n```\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n- What is the maximum distance?\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n\nFor vulnerable tracts, the average distance to the nearest hospital is 4.7 miles away from the tract centroid. The maximum distance is 29.1 miles for tract 9501.04 in Pike County. There are 29 vulnerable tracts with centroids greater than 15 miles from a hospital. I chose the WGS83, Pennsylvania South projection as it uses feet, which is simple to convert into miles.\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(underserved = nearest_hospital_dist > 15)\n\nsum(vulnerable_tracts_proj$underserved)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 29\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n- What percentage of vulnerable tracts are underserved?\n- Does this surprise you? Why or why not?\n\nThere are 29 underserved vulnerable tracts. That's 3.4%. That's much lower than I thought -- I was expecting to more vulnerable tracts in the undreserved category based on my assumption that poorer, more elderly areas often have limited access to necessities.\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n## First, I have to project the counties to fit the tract and hospital data.\n\npa_counties_proj <- pa_counties %>%\n  st_transform(2272)\n\n## NOW I can do the join\nvulnerable_w_county <- vulnerable_tracts_proj %>%\n  st_join(pa_counties_proj, join = st_within)\n\n## It gave me some NAs for COUNTY_NAM when I tried using st_within -- I think because tracts were on the edges of counties? To fix it, I'll take the county names from the NAMELSADCO column that already exists.\n\nvulnerable_w_county <- vulnerable_tracts_proj %>%\n  mutate(COUNTY_NAM = str_remove(NAMELSADCO, \" County\"))\n\n# Aggregate statistics by county\n\ncounty_stats <- vulnerable_w_county %>%\n  st_drop_geometry() %>% ## dropping geometry to avoid issues with grouping and summarizing\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    n_vulnerable_tracts = n(),\n    n_underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = mean(underserved, na.rm = TRUE) * 100,\n    avg_dist_to_hospital = mean(nearest_hospital_dist, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_popE, na.rm = TRUE)\n  )\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n- Which counties have the most vulnerable people living far from hospitals?\n- Are there any patterns in where underserved counties are located?\n\nThe five counties with the highest percentages of underserved vulnerable tracts are: \n  Bradford (100%), Cameron (100%), Forest (100%), Sullivan (100%), and Pike County (58%)\n\nThe counties with the most vulnerable people living far from hospitals are Lancaster, Chester, Erie, Dauphin, and Somerset Counties. They don't all have very high underserved percentages, but their county populations are rather high.\n\nThe most underserved counties (percentage-wise) are often ones with the lower populations, and not near major city centers. \n  \n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n\nlibrary(knitr)\n\n### I want to prioritize based on percent underserved, distance to hospital, and total vulnerable population (in that order).\n\ncounty_stats %>%\n  filter(n_vulnerable_tracts > 0) %>%\n  mutate(\n    priority_score = pct_underserved * 0.5 +\n      (avg_dist_to_hospital / max(avg_dist_to_hospital)) * 100 * 0.3 +\n      (total_vulnerable_pop / max(total_vulnerable_pop)) * 100 * 0.2\n  ) %>%\n  \n  ## Now that I've made the priority score, I'll arrange a table with the top 10 priority counties with descriptive names, rounded numbers, and commas for large numbers.\n  \n  arrange(desc(priority_score)) %>%\n  slice(1:10) %>%\n  mutate(\n    total_vulnerable_pop = formatC(total_vulnerable_pop, format = \"d\", big.mark = \",\"),\n    pct_underserved = round(pct_underserved, 1),\n    avg_dist_to_hospital = round(avg_dist_to_hospital, 1)\n  ) %>%\n  \n  ## Now I'll rename the columns with descriptive titles\n  \nselect(\n  County = COUNTY_NAM,\n  `Vulnerable Tracts` = n_vulnerable_tracts,\n  `Underserved Tracts` = n_underserved,\n  `Percent Underserved` = pct_underserved,\n  `Avg. Distance to Hospital (mi)` = avg_dist_to_hospital,\n  `Vulnerable Population` = total_vulnerable_pop\n  ) %>%\n  \n## Now I'll make the kable to display\n  \n  kable(\n    caption = \"Ten Pennsylvania Counties Prioritized for Healthcare Investment, ranked by compositing underserved population, distances to hospitals, and vulnerable populations\",\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Ten Pennsylvania Counties Prioritized for Healthcare Investment, ranked by compositing underserved population, distances to hospitals, and vulnerable populations\n\n|County     | Vulnerable Tracts| Underserved Tracts| Percent Underserved| Avg. Distance to Hospital (mi)|Vulnerable Population |\n|:----------|-----------------:|------------------:|-------------------:|------------------------------:|:---------------------|\n|Sullivan   |                 4|                  4|               100.0|                           22.7|5,888                 |\n|Cameron    |                 1|                  1|               100.0|                           19.5|2,452                 |\n|Forest     |                 1|                  1|               100.0|                           18.1|2,552                 |\n|Bradford   |                 1|                  1|               100.0|                           16.7|5,171                 |\n|Pike       |                12|                  7|                58.3|                           17.2|19,162                |\n|Huntingdon |                 5|                  2|                40.0|                           15.2|12,675                |\n|Union      |                 3|                  1|                33.3|                            8.0|11,300                |\n|Wayne      |                10|                  2|                20.0|                           11.3|24,884                |\n|Clearfield |                 4|                  1|                25.0|                            9.5|16,867                |\n|Potter     |                 5|                  1|                20.0|                            9.7|10,887                |\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\n## First I'll join county_stats and pa_counties_proj to a new dataset. I need to change COUNTY_NAM in county_stats to uppercase first so they match up.\n\ncounty_stats <- county_stats %>%\n  mutate(COUNTY_NAM = str_to_upper(COUNTY_NAM))\n\ncounty_map_data <- pa_counties_proj %>%\n  left_join(county_stats, by = \"COUNTY_NAM\")\n\n## Now I'll make the map using ggplot2 -- I fiddled around with colors, line widths, and viridis color palettes to find what I thought looked best. I made sure to account for any NAs that may pop up.\n\nggplot() +\n  geom_sf(data = county_map_data,\n          aes(fill = pct_underserved),\n          color = \"white\", linewidth = 0.3) +\n  geom_sf(data = hosputals_proj,\n          shape = 3,\n          size = 1.5,\n          color = \"red\")+\n  scale_fill_viridis_c(\n    name = \"Percent Underserved\",\n    option = \"magma\",\n    direction = -1,\n    na.value = \"grey70\",\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  labs(\n    title = \"Access to Healthcare in Pennsylvania\",\n    Subtitle = \"Percent of vulnerable tracts 15+ miles from the nearest hospital by county\",\n    caption = \"Vulnerable tracts: median income < $35,000 ; elderly population > 25%. \\nHospitals marked as red crosses.\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(size = 10, hjust = 0.5, color = \"grey45\"),\n    plot.caption = element_text(size = 8, color = \"grey55\"),\n    legend.position = \"right\",\n    legend.title = element_text(size = 9),\n    legend.text = element_text(size = 8),\n    plot.margin = margin(10, 10, 10, 10)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\nggplot() +\n  geom_sf(data = pa_counties_proj,\n          fill = \"grey90\", color = \"black\", linewidth = 0.3) +\n  ### Mapped the counties just to have their outlines for better spatial comprehension. \n  ### Next, I'll map vulnerable, adequately served and underserved tracts in two different colors (and make them a little see-through to see the counties underneath)\n  \n  geom_sf(data = vulnerable_tracts_proj %>% filter(!underserved),\n          fill = \"burlywood\", color = NA, alpha = 0.7) +\n  \n  geom_sf(data = vulnerable_tracts_proj %>% filter(underserved),\n          fill = \"darkmagenta\", color = NA, alpha = 0.7) +\n  \n  geom_sf(data = hosputals_proj,\n          shape = 3, size = 1.5, color = \"red\", alpha = 0.7) +\n  \n  labs(title = \"Pennsylvania Vulnerable Census Tracts by Healthcare Access\",\n       subtitle = \"PA Vulnerable tracts by access to hospitals with county and hospital locations\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n### I've elected to do a scatterplot of distance vs. vulnerable population size\n\nggplot(vulnerable_tracts_proj, aes(x = nearest_hospital_dist, y = total_popE)) +\n  geom_point(color = \"darkmagenta\") +\n  scale_x_continuous(labels = function(x) paste0(x, \" mi\")) +\n  labs(\n    title = \"Distance to Hospital vs. Population Size of Vulnerable Census Tracts in PA\",\n    subtitle = \"Each point = one census tract\",\n    x = \"Distance to nearest hospital\",\n    y = \"Census Tract Population\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\nWhereas at low hospital distances, tract population ranges from 0 to nearly 8,000, once hopsital distances surpass 20 miles, only tracts with populations between 1,000 and 3,000 remain. The scatterplot suggests at lower distances, the tract's population matters little, but at higher distances, tract populations are far more likely to be smalller than average in the state.\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nphilly_demo <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  variables = c(\n    total_pop       = \"B01003_001\",  # Total population\n    median_income   = \"B19013_001\",  # Median household income\n    white           = \"B02001_002\",  # White alone\n    black           = \"B02001_003\",  # Black or African American alone\n    asian           = \"B02001_005\",  # Asian alone\n    hispanic        = \"B03003_003\"   # Hispanic or Latino\n  ),\n  year = 2024,\n  output = \"wide\"\n)\n\n## Now we've got our demographic data for philly census tracts. Let's make some percent population columns for racial data.\n\nphilly_demo <- philly_demo %>%\n  mutate(\n    pct_white = whiteE / total_popE * 100,\n    pct_black = blackE / total_popE * 100,\n    pct_asian = asianE / total_popE * 100,\n    pct_hispanic = hispanicE / total_popE * 100,\n    majority_minority = (pct_white < 50)\n  )\n\nphilly_tracts <- census_tracts %>%\n  filter(COUNTYFP == \"101\") %>%\n  left_join(philly_demo, by = \"GEOID\") %>%\n  st_transform(2272)\n\n## Had to fix the variable names because there were duplicates\nphilly_tracts <- philly_tracts %>%\n  mutate(\n    total_pop = total_popE.x,\n    median_income = median_incomeE.x\n  ) %>%\n  select(-ends_with(\".x\"), -ends_with(\".y\"), -ends_with(\"M\"),\n         -NAME)\n\n## Now let's load the data from OpenDataPhilly for trees and parks. Once loaded, we also have to transform them to be in the same projection.\n\nphilly_trees <- st_read(\"data/ppr_tree_inventory_2025.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ppr_tree_inventory_2025' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_2/data/ppr_tree_inventory_2025.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 151726 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8380434 ymin: 4847791 xmax: -8344373 ymax: 4885938\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nphilly_parks <- st_read(\"data/PPR_Properties.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Properties' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_2/data/PPR_Properties.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 504 features and 25 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8380525 ymin: 4847239 xmax: -8344359 ymax: 4885123\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nphilly_trees <- philly_trees %>%\n  st_transform(2272)\n\nphilly_parks <- philly_parks %>%\n  st_transform(2272)\n\nst_crs(philly_parks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:2272 \n  wkt:\nPROJCRS[\"NAD83 / Pennsylvania South (ftUS)\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"SPCS83 Pennsylvania South zone (US survey foot)\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",39.3333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-77.75,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",40.9666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",39.9333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1968500,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.\"],\n        BBOX[39.71,-80.53,41.18,-74.72]],\n    ID[\"EPSG\",2272]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(philly_trees)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:2272 \n  wkt:\nPROJCRS[\"NAD83 / Pennsylvania South (ftUS)\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"SPCS83 Pennsylvania South zone (US survey foot)\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",39.3333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-77.75,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",40.9666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",39.9333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1968500,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.\"],\n        BBOX[39.71,-80.53,41.18,-74.72]],\n    ID[\"EPSG\",2272]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(philly_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:2272 \n  wkt:\nPROJCRS[\"NAD83 / Pennsylvania South (ftUS)\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"SPCS83 Pennsylvania South zone (US survey foot)\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",39.3333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-77.75,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",40.9666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",39.9333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1968500,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.\"],\n        BBOX[39.71,-80.53,41.18,-74.72]],\n    ID[\"EPSG\",2272]]\n```\n\n\n:::\n\n```{.r .cell-code}\n### mapped it just to make sure it all looks alright\nplot(st_geometry(philly_tracts), border = \"grey60\")\nplot(st_geometry(philly_trees), col = \"darkgreen\", add = TRUE)\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n### Now let's make a summary table of some basic info about the data\nsummary_table <- data.frame(\n  Dataset = c(\"Census Tracts\", \"Parks\", \"Street Trees\"),\n  Features = c(nrow(philly_tracts), nrow(philly_parks), nrow(philly_trees)),\n  Geometry = c(\"Polygon\", \"Polygon\", \"Point\"),\n  CRS = c(\"EPSG 2272\", \"EPSG 2272\", \"EPSG 2272\")\n)\n\nkable(summary_table,\n      col.names = c(\"Dataset\", \"No. of Features\", \"Geometry Type\", \"CRS\"),\n      caption = \"Summary of Datasets Used in Green Space Equity Analysis\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Datasets Used in Green Space Equity Analysis\n\n|Dataset       | No. of Features|Geometry Type |CRS       |\n|:-------------|---------------:|:-------------|:---------|\n|Census Tracts |             408|Polygon       |EPSG 2272 |\n|Parks         |             504|Polygon       |EPSG 2272 |\n|Street Trees  |          151726|Point         |EPSG 2272 |\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n- What is the data source and date?\n- How many features does it contain?\n- What CRS is it in? Did you need to transform it?\n\nI chose to use a tree inventory dataset from OpenDataPhilly, a park polygon shapefile from PPR, and census tracts including race and income demographics from the 5-year ACS 2024. I decided to use this data to observe any trends between access to green space/nature and demographics in Philly.\n\nThe tree inventory point dataset is from 2025 and contains over 150,000 entries with 7 columns, including the tree's coordinates, type/species, and year.\nThe parks shapefile from PPR is from 2018, which is older than the other data in this analysis, but is less concerning since parkspace changes much less over time than trees or demographics. It contains 504 entries with 26 columns providing details on the type, use, geometry, and more. \nThe ACS demographic and tract data is from 2024. There are 408 entries and columns for geometry, demographics, etc.\n\nAll the data was transformed to NAD83, Pennsylvania South (ftUS). \n\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n\"Do low-income and minority neighborhoods have equitable access to green space?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\n## First, make a half-mile buffer around parks. dist = 2640 because units are in feet. A half mile is a good measure of convenient walking distance.\nparks_buffer <- st_buffer(philly_parks, dist = 2640)\nparks_buffer_union <- st_union(parks_buffer)\n## I also combined them with st_union so they don't all overlap and count tracts twice in later analysis\n\n## Now let's count how many trees are in each tract\ntrees_per_tract <- st_join(philly_tracts, philly_trees) %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(tree_count = n())\n\n## Calculate park area in each tract (and fix with st_make_valid)\nphilly_parks <- st_make_valid(philly_parks)\nphilly_tracts <- st_make_valid(philly_tracts)\n\npark_tract_intersection <- st_intersection(philly_tracts, philly_parks)\n\npark_area_per_tract <- park_tract_intersection %>%\n  st_drop_geometry() %>%\n  mutate(park_area = as.numeric(st_area(park_tract_intersection))) %>%\n  group_by(GEOID) %>%\n  summarise(total_park_area = sum(park_area, na.rm = TRUE))\n\n## Alright now we join them back to philly_tracts and get per capita info\nphilly_tracts <- philly_tracts %>%\n  left_join(trees_per_tract, by = \"GEOID\") %>%\n  left_join(park_area_per_tract, by = \"GEOID\") %>%\n  mutate(\n    tree_count = replace_na(tree_count, 0),\n    total_park_area = replace_na(total_park_area, 0),\n    trees_per_capita = tree_count / total_pop,\n    park_area_per_capita = total_park_area / total_pop\n  )\n\n## When checking the data, there were some issues with tracts with 0 population, so I had to count them as NA instead to avoid dividing by 0.\nphilly_tracts <- philly_tracts %>%\n  mutate(\n    trees_per_capita = ifelse(total_pop > 0, tree_count / total_pop, NA),\n    park_area_per_capita = ifelse(total_pop > 0, total_park_area / total_pop, NA)\n  )\n\nsummary(philly_tracts$trees_per_capita)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n 0.00516  0.04569  0.07550  0.14553  0.13335 12.45588       17 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(philly_tracts$park_area_per_capita)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n     0.0      0.0     32.8   2667.3    116.5 777882.3       17 \n```\n\n\n:::\n\n```{.r .cell-code}\n## Ok, now that we have the parks buffered, our per capita data, and per tract data, we can start comparing green space allocation by income and minority statistics for census tracts.\n\n#First, let's check if tracts have centroids within the .5 mile parks buffer \n\ntract_centroids <- st_centroid(philly_tracts)\n\nphilly_tracts <- philly_tracts %>%\n  mutate(park_access = lengths(st_intersects(tract_centroids, parks_buffer_union)) > 0)\n\n#Now we can break the demographics up into groups to better compare metrics\n\n### First, let's make two income levels: above and below a median income of $40,000. With this, we can summarise park access (rounded) by income group.\nphilly_tracts %>%\n  st_drop_geometry() %>%\n  mutate(income_group = ifelse(median_income < 40000, \"Low Income <$40k\", \"Higher Income >$40k\")) %>%\n  group_by(income_group) %>%\n  summarise(n_tracts = n(),\n            pct_park_access = round(mean(park_access, na.rm = TRUE) * 100, 1),\n            avg_trees_per_capita = round(mean(trees_per_capita, na.rm = TRUE), 3),\n            avg_park_area_per_capita = round(mean(park_area_per_capita, na.rm = TRUE), 1)\n            ) %>%\n### Now, let's make a table with clean column names and a caption to show the summary.\n  kable(\n    col.names = c(\"Income Level\", \"No. of Tracts\", \"% within .5 miles of a park\", \"Avg Trees per Capita\", \"Avg Park Area per Capita (sqft)\"),\n    caption = \"Nature/Green Space Access by Income across Philadelphia Census Tracts\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Nature/Green Space Access by Income across Philadelphia Census Tracts\n\n|Income Level        | No. of Tracts| % within .5 miles of a park| Avg Trees per Capita| Avg Park Area per Capita (sqft)|\n|:-------------------|-------------:|---------------------------:|--------------------:|-------------------------------:|\n|Higher Income >$40k |           296|                        97.0|                0.117|                           837.9|\n|Low Income <$40k    |            79|                        98.7|                0.082|                           101.3|\n|NA                  |            33|                        75.8|                0.984|                         49180.9|\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now let's make another summary table looking at green space access for majority-minority tracts vs. majority white tracts. It will mostly follow the same steps as the previous table.\n\nphilly_tracts %>%\n  st_drop_geometry() %>%\n  group_by(majority_minority) %>%\n  summarise(\n    n_tracts = n(),\n    pct_park_access = round(mean(park_access, na.rm = TRUE) * 100, 1),\n    avg_trees_per_capita = round(mean(trees_per_capita, na.rm = TRUE), 3),\n    avg_park_area_per_capita = round(mean(park_area_per_capita, na.rm = TRUE), 1)\n  ) %>%\n  mutate(majority_minority = ifelse(majority_minority, \"Majority-Minority\", \"Majority White\")) %>%\n  kable(\n    col.names = c(\"Race Demographics\", \"No. of Tracts\", \"% within .5 miles of a park\", \"Avg Trees per Capita\", \"Avg Park Area per Capita (sqft)\"),\n    caption = \"Nature/Green Space Access by Race Demographics across Philadelphia Census Tracts\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Nature/Green Space Access by Race Demographics across Philadelphia Census Tracts\n\n|Race Demographics | No. of Tracts| % within .5 miles of a park| Avg Trees per Capita| Avg Park Area per Capita (sqft)|\n|:-----------------|-------------:|---------------------------:|--------------------:|-------------------------------:|\n|Majority White    |           141|                        97.9|                0.252|                          7180.8|\n|Majority-Minority |           250|                        96.8|                0.086|                           121.7|\n|NA                |            17|                        58.8|                  NaN|                             NaN|\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now that we have two summary tables, let's make a map to visualize trees per capita across Philly census tracts with park buffers. It should give a general idea of which parts have differing levels of nature access.\n\nggplot() +\n  geom_sf(data = philly_tracts, aes(fill = trees_per_capita), color = \"white\", linewidth = 0.1) + #Mapping trees per capita in each tract\n  geom_sf(data = parks_buffer_union, fill = adjustcolor(\"darkgreen\", alpha = 0.2), color = \"darkgreen\", linewidth = 0.3) + #Mapping the parks buffers and making them transparent as not to drown out the rest of the map\n  geom_sf(data = philly_parks, fill = \"darkgreen\", color = NA) +\n  scale_fill_viridis_c(\n    name = \"Trees per Capita\",\n    option = \"cividis\",\n    na.value = \"grey80\",\n    limits = c(0, 0.25),\n    oob = scales::squish\n  ) + #Here, I just made the parks dark green, and visualized the trees per capita using a color gradient in each tract. There were some very high outliers, so I used limits and oob = scales::squish to set a limit for the color scale, and make anything above it appear as the max value (0.25 in this case)\n  labs(\n    title = \"Trees per Capita and Park Access in Philadelphia\",\n    caption = \"Park buffers represent a 10-minute walking distance. Dark green areas are parks.\") +\n   #Added a title and caption\n  theme_void() # Got rid of the grey background grid\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nWhile the higher and lower income groups have similar near-100% access to a park within 0.5 miles, their average trees per capita and average park area per capita vastly Differ. Higher income tracts have 1.4x as many trees per capita and over 8x as much park area per capita. Majority White and Majority Minority tracts also have similar access to a park within .5 miles, but too have vastly differing per capita metrics. Majority White tracts have nearly 3x more trees per capita, and a staggering 59x greater avg park area per capita. Mapped, it’s clear that white and wealth areas in Center City, NW Philly, and areas along the Delaware river have far greater trees per capita, which aligns with the trends seen in the summary tables.\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}