{
  "hash": "ba23024e9d5c276c69fe82bad9550a66",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"William Rantala\"\ndate: today\nformat: \n  html:\n    code-fold: show\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\nIn this lab, you will apply the spatial predictive modeling techniques demonstrated in the class exercise using a different 311 service request type of your choice as the predictor variable to predict burglaries in Chicago. You will build a complete spatial predictive model, document your process, and interpret your results.\n\n### Learning Objectives\n\nBy completing this assignment, you will demonstrate your ability to:\n\n-   Adapt example code to analyze a new dataset\n-   Build spatial features for predictive modeling\n-   Apply count regression techniques to spatial data\n-   Implement spatial cross-validation\n-   Interpret and communicate model results\n-   Critically evaluate model performance\n\n------------------------------------------------------------------------\n\n## Step 1: Choose Your 311 Violation Type\n\nI choose Pothole Repair Requests to use as a predictor in this assignment. My reasoning for choosing potholes as a predictor is that under-served and maintenance-neglected areas often have higher crime rates. In this lab, we will run some spatial analyses and create models to see if that is true.\n\n### Getting the Data\n\nTo get the data, visit the Chicago 311 Service Requests dataset:\n\n<https://data.cityofchicago.org/stories/s/311-Dataset-Changes-12-11-2018/d7nq-5g7t>\n\n## Step 2: Analysis\n\n#### Part 1: Data Loading & Exploration\n\n-   Load your 311 data and Chicago spatial boundaries\n-   Create visualizations showing the spatial distribution of your violation type\n-   Describe patterns you observe\n\nFirst, let's set up and load in our necessary r libraries, format some outputs, and create a consistent theme\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### First let's load necessary libraries\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\n\n\n# Spatstat for analyzing point patterns - split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # This gets rid of scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n\n# Create consistent theme for visualizations\ntheme_crime <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_crime())\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Working directory: /Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_4 \n```\n\n\n:::\n:::\n\n\nNext, let's load in our Chicago spatial data, 311 violation data, and burglary data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 61,766\nColumns: 18\n$ CREATION.DATE                      <chr> \"12/31/2017\", \"12/31/2017\", \"12/31/…\n$ STATUS                             <chr> \"Completed\", \"Completed\", \"Complete…\n$ COMPLETION.DATE                    <chr> \"01/04/2018\", \"01/09/2018\", \"01/05/…\n$ SERVICE.REQUEST.NUMBER             <chr> \"17-08705113\", \"17-08699339\", \"17-0…\n$ TYPE.OF.SERVICE.REQUEST            <chr> \"Pothole in Street\", \"Pothole in St…\n$ CURRENT.ACTIVITY                   <chr> \"Final Outcome\", \"Final Outcome\", \"…\n$ MOST.RECENT.ACTION                 <chr> \"Pothole Patched\", \"Pothole Patched…\n$ NUMBER.OF.POTHOLES.FILLED.ON.BLOCK <dbl> 1, 1, 5, NA, NA, 5, NA, 18, 1, 1, 4…\n$ STREET.ADDRESS                     <chr> \"3400 N LOCKWOOD AVE\", \"2205 N SOUT…\n$ ZIP                                <int> 60641, 60614, 60601, 60660, 60611, …\n$ X.COORDINATE                       <dbl> 1140431, 1166624, 1178304, 1168584,…\n$ Y.COORDINATE                       <dbl> 1922094, 1914774, 1901842, 1938719,…\n$ Ward                               <int> 30, 2, 42, 48, 42, 12, 48, 12, 13, …\n$ Police.District                    <int> 16, 18, 1, 20, 18, 10, 20, 10, 8, 2…\n$ Community.Area                     <int> 15, 7, 32, 77, 8, 30, 77, 30, 64, 4…\n$ SSA                                <int> NA, NA, NA, NA, NA, NA, NA, NA, 3, …\n$ LOCATION                           <chr> \"(41.942363406897, -87.759409952944…\n$ geometry                           <POINT [m]> POINT (347592.2 585859.4), PO…\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded potholes data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of potholes: 61766 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 01/01/2017 to 12/31/2017 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `burglaries' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_4/data/burglaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 7482 features and 22 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 340492 ymin: 552959.6 xmax: 367153.5 ymax: 594815.1\nProjected CRS: NAD83(HARN) / Illinois East\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 7,482\nColumns: 23\n$ ID       <int> 10801247, 10801593, 10801602, 10801904, 10801956, 10802305, 1…\n$ Cs_Nmbr  <chr> \"JA100159\", \"JA100586\", \"JA100376\", \"JA100943\", \"JA101022\", \"…\n$ Date     <date> 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-02, 2017-01-01, …\n$ Block    <chr> \"048XX N KEDZIE AVE\", \"054XX W CHICAGO AVE\", \"057XX S MOZART …\n$ IUCR     <chr> \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610…\n$ Prmry_T  <chr> \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"…\n$ Dscrptn  <chr> \"FORCIBLE ENTRY\", \"FORCIBLE ENTRY\", \"FORCIBLE ENTRY\", \"FORCIB…\n$ Lctn_Ds  <chr> \"RESTAURANT\", \"SMALL RETAIL STORE\", \"RESIDENCE-GARAGE\", \"RESI…\n$ Arrest   <chr> \"true\", \"false\", \"false\", \"true\", \"false\", \"false\", \"false\", …\n$ Domestc  <chr> \"false\", \"false\", \"false\", \"false\", \"false\", \"false\", \"false\"…\n$ Beat     <int> 1713, 1524, 824, 722, 724, 1723, 732, 935, 1432, 334, 2533, 1…\n$ Distrct  <int> 17, 15, 8, 7, 7, 17, 7, 9, 14, 3, 25, 12, 16, 25, 3, 4, 12, 1…\n$ Ward     <int> 33, 37, 16, 6, 17, 39, 17, 3, 1, 7, 37, 1, 38, 31, 5, 7, 1, 4…\n$ Cmmnt_A  <int> 14, 25, 63, 69, 67, 16, 68, 61, 21, 43, 25, 24, 15, 20, 43, 4…\n$ FBI_Cod  <chr> \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"…\n$ X_Crdnt  <int> 1154172, 1139598, 1158356, 1176576, 1168818, 1150614, 1172237…\n$ Y_Crdnt  <int> 1931913, 1904799, 1866496, 1859716, 1860109, 1928503, 1856217…\n$ Year     <int> 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2…\n$ Updtd_O  <date> 2017-02-14, 2017-02-14, 2017-02-14, 2018-02-10, 2017-02-14, …\n$ Latitud  <dbl> 41.96900, 41.89488, 41.78940, 41.77041, 41.77166, 41.95971, 4…\n$ Longitd  <dbl> -87.70849, -87.76275, -87.69490, -87.62830, -87.65672, -87.72…\n$ Locatin  <chr> \"(41.968999706, -87.708494241)\", \"(41.894875219, -87.76274673…\n$ geometry <POINT [m]> POINT (351792.8 588847.4), POINT (347350.6 580583), POI…\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded burglary data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of burglaries: 7482 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 2017-01-01 to 2018-01-01 \n```\n\n\n:::\n:::\n\n\nNow let's visualize potholes in Chicago\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map of potholes\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = potholes, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Pothole Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(potholes))\n  )\n\n# Density surface map of potholes\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(potholes)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork to see them side by side\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Potholes in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\nIn the created maps, we can see that there have been potholes reported on just about every street in the city. In the kernel density map, we can see that reported potholes are concentrated downtown and on the north side more than elsewhere. Based on knowledge of the city, one could hypothesize that the high density of potholes downtown and the north side is due to residents reporting potholes more than south and west side residents.\n\nNow, let's visualize Burglaries in Chicago (same process as the pothole maps)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map of burglaries\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = burglaries, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Burglary Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(burglaries))\n  )\n\n# Density surface map of burglaries\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork to see them side by side\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Burglaries in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-points-1.png){width=960}\n:::\n:::\n\n\nWhile there are far fewer recorded burglaries as there are potholes in Chicago, their density maps show somewhat similar patterns: downtown and Northwest of downtown, as well as some parts of the South side have higher densities. That being said, burglaries seem to be far denser on the South and West sides than potholes.\n\n#### Part 2: Fishnet Grid Creation\n\n-   Create a 500m x 500m fishnet grid\n-   Aggregate your violations to grid cells\n-   Visualize the count distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number()) %>%\n  st_transform('ESRI:102271') \n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\n# View basic info\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n\n```{.r .cell-code}\n# Spatial join pothole data to cells to see which cell contains each pothole\npotholes_fishnet <- st_join(potholes, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countPotholes = n()) \n\n\nglimpse(potholes_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,204\nColumns: 2\n$ uniqueID      <int> 38, 39, 47, 50, 90, 91, 92, 93, 94, 96, 101, 102, 103, 1…\n$ countPotholes <int> 4, 1, 1, 10, 5, 1, 3, 8, 1, 1, 1, 29, 27, 20, 12, 6, 1, …\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(potholes_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System: NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# Join back to fishnet (cells with 0 potholes will be NA)\nfishnet <- fishnet %>%\n  left_join(potholes_fishnet, by = \"uniqueID\") %>%\n  mutate(countPotholes = replace_na(countPotholes, 0))\n\n# Summary statistics\nsummary(fishnet$countPotholes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    8.00   20.00   25.03   37.00  174.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero potholes:\", \n    sum(fishnet$countPotholes == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countPotholes == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero potholes: 255 / 2458 ( 10.4 %)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualize aggregated counts\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countPotholes), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Potholes\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 25, 50, 100)\n  ) +\n  labs(\n    title = \"Pothole Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nWhen potholes are aggregated to 500m x 500m cells, we get a clearer understanding of the concentrations of reported potholes. Once again, this map shows the greatest concentration of potholes near the loop downtown, and greater densities on the North Side. There are some pockets of great potholes reported on the South and Southwest sides, but a lot of the region has a lower concentration. It should be noted that in many of the deep south regions with fewer potholes reported also have lower population densities than downtown and many regions on the north side like Lakeview and Lincoln Park.\n\nNow, let's add Burglaries to the fishnet and visualize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\n# Join back to fishnet\nfishnet <- fishnet %>%\n  left_join(burglaries_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n# Visualize aggregated counts of burglaries in each cell\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Burglaries\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 1, 5, 10, 20, 40)\n  ) +\n  labs(\n    title = \"Burglary Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nIn this map of burglary counts by cell we can see that the cells with the greatest burglary counts are in the same areas of the South and West/NW sides as seen in other visualizations.\n\n#### Part 3: Spatial Features\n\n-   Calculate k-nearest neighbor features\n-   Perform Local Moran's I analysis\n-   Identify hot spots and cold spots\n-   Create distance-to-hotspot measures\n-   Join any additional contextual data if you are looking for more to do and really get into this (e.g., demographics, land use)\n\nLet's create our Kernel Density Estimate baseline that we will use to compare our model to later\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert burglaries to ppp (point pattern) format for spatstat\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_burglaries)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of burglary locations\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-kde-1.png){width=768}\n:::\n:::\n\n\nThe kernal density map of burglaries in Chicago reinforces what we learned from our earlier visualizations in that the greatest concentrations are clustered on the South side and West/NW of downtown. There are large low density areas on the deep South of the city where Illinois borders Indiana, and far Northwest near O'Hare. We will use the Kernel Density Estimate map as a baseline to compare our model to later.\n\nHere, I did the same for potholes to see how the kernel density maps compare\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert potholes to ppp (point pattern) format for spatstat\npotholes_ppp <- as.ppp(\n  st_coordinates(potholes),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_potholes <- density.ppp(\n  potholes_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_potholes_raster <- rast(kde_potholes)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_potholes_value = terra::extract(\n      kde_potholes_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n:::\n\n\nNow we've calculated kernel densities for potholes reported in Chicago. Next, let's visualize pothole KDE on a map of Chicago\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_potholes_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of reported pothole locations\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\nThe KDE map of reported potholes in Chicago shows similar patterns to the count map from earlier, but does a better job at showing higher value clusters (especially on the South Side where the pattern is less obvious in the count map). The KDE map confirms the count map's visual storytelling by highlighting the high cluster of values in downtown and much of the North Side of the city.\n\nLet's visualize potholes and burglaries with each other to better see if there is a visual correlation\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countPotholes), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"magma\") +\n  labs(title = \"Potholes 311 Calls\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Burglaries\") +\n  theme_crime()\n\np1 + p2 +\n  plot_annotation(title = \"Are potholes and burglaries correlated?\")\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\nWith potholes and burglaries mapped side by side, there is a clear similar patter of higher concentrations on the south side, with a lower density between downtown and the south, and a higher concentration radiating West/NW from downtown. Otherwise, it looks like potholes are far more common on more of the North side than are burglaries.\n\nLet's get k-nearest neighbors for potholes. We'll use knn potholes as a predictor in our model later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Count in a cell is one measure. Distance to the nearest 3 nearest reported potholes captures local context.s\n# Calculate mean distance to 3 nearest reported potholes\n# (Do this OUTSIDE of mutate to avoid sf conflicts)\n\n# Get coordinates\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\npothole_coords <- st_coordinates(potholes)\n\n# There are a 12 NAs in pothole_coords. Since it's only 12, we'll go ahead and drop them.\npothole_coords_clean <- na.omit(pothole_coords)\n\n# Calculate k nearest neighbors and distances\nnn_result <- get.knnx(pothole_coords_clean, fishnet_coords, k = 3)\n\n# Add to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    potholes.nn = rowMeans(nn_result$nn.dist)\n  )\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$potholes.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   5.709   62.127   96.399  157.068  168.858 1896.400 \n```\n\n\n:::\n:::\n\n\nThe mean distance to the 3 nearest reported potholes is 90.6696 meters\n\nNext, we'll ruan a Local Moran's I to assess spatial autocorrelation of pothole counts across cells.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Now let's run a Local Moran's I to assess spatial autocorrelation of pothole counts.\n\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  # Calculate Local Moran's I\n  local_moran <- localmoran(data[[variable]], weights)\n  \n  # Classify clusters\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply to abandoned cars\nfishnet <- calculate_local_morans(fishnet, \"countPotholes\", k = 5)\n```\n:::\n\n\nNow that we've ran our local Moran's I, let's visualize it on a map\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Pothole Clusters\",\n    subtitle = \"High-High = Hot spots of pothole reports\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-morans-1.png){width=768}\n:::\n:::\n\n\nOn the map, we see many high-high zones (high pothole counts near other high pothole counts). Most of those 'hotspots' are located downtown and on the north side of the city, with a few small ones dotted on the south side of the city. The low-low zones are highly concentrated on the far south side near the Illinois-Indiana border, where very few people live and most of the land uses are natural or industrial.\n\nLet's get the centroids of those \"hotspots\" to use for spatial analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\n\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to pothole hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to pothole hot spots\n  - Number of hot spot cells: 226 \n```\n\n\n:::\n:::\n\n\nNow, let's pull some more 311 violations in Chicago to use for regression/model building. In this model, we'll also use street light outage reports as a predictor. I chose light outage reports as another predictor under the assumption that there may be more street light outages in more under-served parts of the city.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Use st_read to read the GeoJSON of street light outages\nlightout <- st_read(\"data/Street_Lights_Out.geojson\") %>% \n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Street_Lights_Out' from data source \n  `/Users/wilrantala/Desktop/Wil-Rantala---CPLN-5920-Portfolio/labs/lab_4/data/Street_Lights_Out.geojson' \n  using driver `GeoJSON'\nreplacing null geometries with empty geometries\nSimple feature collection with 490937 features and 23 fields (with 459 geometries empty)\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -87.93529 ymin: 41.6446 xmax: -87.52453 ymax: 42.02255\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n### Let's make a new variable 'lighsout' that has no NA geographies\nlightsout <- na.omit(lightout)\n\n### The date range for light outages is different than our pothole data. In order to assess the data sets over the same date range, we'll remove lights out reports that fall outside of 2017\nlightsout <- lightsout %>%\n  filter(between(creation_date, as.Date(\"2017-01-01\"), as.Date(\"2017-12-31\")))\n\n# Check the data\ncat(\"\\n✓ Loaded lights out data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded lights out data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of reported lights out:\", nrow(lightsout), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of reported lights out: 74253 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - CRS:\", st_crs(lightsout)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Date range:\", format(min(lightsout$creation_date, na.rm = TRUE)), \"to\", \n    format(max(lightsout$creation_date, na.rm = TRUE)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 2017-01-01 to 2017-12-31 \n```\n\n\n:::\n:::\n\n\nLet's visualize those street light outages in Chicago just like we did earlier for burglaries and potholes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map\np5 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = lightsout, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Street light outage Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(lightsout))\n  )\n\n# Density surface using modern syntax\np6 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(lightsout)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork (modern approach)\np5 + p6 + \n  plot_annotation(\n    title = \"Spatial Distribution of Street Light Outages in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\nLet's aggregate street light outage reports to the same fishnet we created for potholes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join: which cell contains each light outage?\nlights_fishnet <- st_join(lightsout, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countLightsOut = n())\n\n# Join back to fishnet\nfishnet <- fishnet %>%\n  left_join(lights_fishnet, by = \"uniqueID\") %>%\n  mutate(countLightsOut = replace_na(countLightsOut, 0))\n\n# Summary statistics\nsummary(fishnet$countLightsOut)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    7.25   23.00   30.18   45.00  213.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero Light Outages:\", \n    sum(fishnet$countLightsOut == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countLightsOut == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero Light Outages: 317 / 2458 ( 12.9 %)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualize aggregated counts\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countLightsOut), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Street Light Outages\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 25, 50, 100, 200)\n  ) +\n  labs(\n    title = \"Street Light Outage Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe light outage fishnet map shows a slightly different pattern than the pothole map. In the light outage map, there is a similar cluster of low values in the deep south side and in the near south, but they differ greatly on the north side, where there are fewer light outages. The map of light outages appears to have some similar patterns as the burglary map with higher concentrations on the west side.\n\n#### Part 4: Count Regression Models\n\n-   Fit Poisson regression\n-   Fit Negative Binomial regression\n-   Compare model fit (AIC)\n\nNow, lets start running regressions to gain a statistical understanding of the relationship between our predictors (street light outages, potholes, pothole nearest neighbors). We'll use police districts for our spatial cross-validation later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))  # Remove cells outside districts\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cells: 1708 \n```\n\n\n:::\n:::\n\n\nNow let's move on to fitting a Poisson Regression. We can use a Poisson Regression because burglaries are count data (0, 1, 2, 3, etc...) First, we must clean the dataset for the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create clean modeling dataset with only the necessary columns\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    countPotholes,\n    potholes.nn,\n    countLightsOut,\n    dist_to_hotspot,\n    \n  ) %>%\n  na.omit()  # Remove any remaining NAs\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 1708 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Variables:\", ncol(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Variables: 7 \n```\n\n\n:::\n:::\n\n\nNow that we have a clean dataset, we can fit a Poisson regression to look at how our predictors are correlated with burglary counts in each 500x500m cell.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Poisson regression\nmodel_poisson <- glm(\n  countBurglaries ~ countPotholes + potholes.nn + countLightsOut + \n    dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\n# Summary\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ countPotholes + potholes.nn + \n    countLightsOut + dist_to_hotspot, family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                    Estimate   Std. Error z value            Pr(>|z|)    \n(Intercept)      1.425304272  0.050829810  28.041 <0.0000000000000002 ***\ncountPotholes   -0.000979097  0.000747388  -1.310              0.1902    \npotholes.nn     -0.004297080  0.000254340 -16.895 <0.0000000000000002 ***\ncountLightsOut   0.008370116  0.000393838  21.253 <0.0000000000000002 ***\ndist_to_hotspot -0.000022082  0.000009376  -2.355              0.0185 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6710.3  on 1707  degrees of freedom\nResidual deviance: 5305.2  on 1703  degrees of freedom\nAIC: 9375.5\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nIn the Poisson regression, our results show that three of our four predictors are statistically significant (p values effectively zero), but countPotholes was found to be less significant, with a p value of 0.1902, thus its significance questionable at best.\n\nThe intercept is 1.425, which means when all predictors are zero, the predicted burglary count is e\\^1.425 = 4.157 burglaries.\n\ncountPotholes has a coefficient of 0.000979097, meaning each additional reported pothole in that cell is correlated with a 0.098% increase in burglaries in that cell. Again, countPotholes' coefficient was found to be less statistically significant than the other predictors.\n\npotholes.nn has a coefficient of -0.004297080, meaning each additional meter it takes to reach the 3 nearest potholes (on average) is correlated with a 0.43% decrease in the number of burglaries in that cell.\n\ncountLightsOut has a coefficient of 0.008370116, meaning each additional reported street light outage is correlated with a 0.84% increase in the number of burglaries in that cell.\n\ndist_to_hotspot has a coefficient of -0.000022082, meaning each additional meter of distance away from the nearest hotspot of potholes is correlated to a 0.002% decrease in the number of burglaries in that cell. (i.e., the closer to a pothole hotspot you are, the greater number of burglaries are likely to be found). The coefficient value is very small, but is a measure per meter, so cumulatively it can have a large statistical effect.\n\nPoisson regression only works as an effective method when dispersion is limited. Let's check our dispersion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) / \n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 3.53 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Consider Negative Binomial model.\n```\n\n\n:::\n:::\n\n\nSince the dispersion is too great for the Poisson model to be trustworthy, we will also run a Negative Binomial Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Negative Binomial model\nmodel_nb <- glm.nb(\n  countBurglaries ~ countPotholes + potholes.nn + countLightsOut + \n    dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Summary\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ countPotholes + potholes.nn + \n    countLightsOut + dist_to_hotspot, data = fishnet_model, init.theta = 1.475653881, \n    link = log)\n\nCoefficients:\n                   Estimate  Std. Error z value            Pr(>|z|)    \n(Intercept)      1.50753811  0.09585308  15.728 <0.0000000000000002 ***\ncountPotholes   -0.00209858  0.00144932  -1.448              0.1476    \npotholes.nn     -0.00568201  0.00043453 -13.076 <0.0000000000000002 ***\ncountLightsOut   0.01089416  0.00087142  12.502 <0.0000000000000002 ***\ndist_to_hotspot -0.00003079  0.00001712  -1.798              0.0721 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.4757) family taken to be 1)\n\n    Null deviance: 2424.6  on 1707  degrees of freedom\nResidual deviance: 1833.3  on 1703  degrees of freedom\nAIC: 7642.7\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.4757 \n          Std. Err.:  0.0799 \n\n 2 x log-likelihood:  -7630.6730 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare AIC (lower is better)\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 9375.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 7642.7 \n```\n\n\n:::\n:::\n\n\nInterpreting binomial regression coefficients is similar as with poisson coefficients.\n\nThe intercept coefficient of 1.50753811 means that when all predictors equal zero, the predicted count of burglaries = e\\^1.50753811 = 4.513\n\nThe countPotholes coefficient of -0.00209858 means that (assuming all other are unchanged) an increase in one counted pothole is correlated with a 0.21% decrease in burglaries in that cell. In the negative binomial regression, countPotholes is even less statistically significant of a predictor than in the poisson regression. Its p value of 0.1476 renders it statistically insignificant.\n\nThe potholes.nn coefficient of -0.00568201 means that an increase of 1 meter of the average distance to the three nearest reported potholes is correlated with a 0.57% decrease of burglaries in that cell.\n\nThe countLightsout coefficient of 0.01089416 means that an increase of 1 reported street light outage in a cell is correlated to a 1.09% increase of burglaries in that cell.\n\nthe dist_to_hotspot coefficient of -0.00003079 means that an increase of 1 meter of distance from the nearest hotspot of potholes is correlated with a 0.003% decrease of burglaries in the cell. The p value of dist_to_hotspot in the negative binomial regression is 0.0721, meaning its significance is questionable compared to other variables, but still far more likely to be significant than not.\n\n##### Comparing Poisson and Negative Binomial Regression Results\n\nPoisson AIC: 9375.5 Negative Binomial AIC: 7642.7\n\nNegative binomial regression is more flexible as it allows for greater dispersion in the data. Our AIC results show that the negative binomial model is more effective than the poisson at fitting the data presented. Under poisson regression, standard errors are underestimated if there is great dispersion.\n\n#### Part 5: Spatial Cross-Validation (2017)\n\n-   Implement Leave-One-Group-Out cross-validation on 2017 data\n-   Calculate and report error metrics (MAE, RMSE)\n\nSpatial Cross-Validation tests the model on unseen data by training the model on data from nearby cells and testing on an \"unseen\" cell.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique districts\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model on training data\n  model_cv <- glm.nb(\n    countBurglaries ~ countPotholes + potholes.nn + countLightsOut + \n    dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict on test data\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, test_data, type = \"response\")\n    )\n  \n  # Calculate metrics\n  mae <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  # Store results\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district, \n      \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 22 - District 5 - MAE: 2 \n  Fold 2 / 22 - District 4 - MAE: 2.21 \n  Fold 3 / 22 - District 22 - MAE: 2.66 \n  Fold 4 / 22 - District 6 - MAE: 4.03 \n  Fold 5 / 22 - District 8 - MAE: 2.87 \n  Fold 6 / 22 - District 7 - MAE: 3.31 \n  Fold 7 / 22 - District 3 - MAE: 5.59 \n  Fold 8 / 22 - District 2 - MAE: 2.86 \n  Fold 9 / 22 - District 9 - MAE: 2.02 \n  Fold 10 / 22 - District 10 - MAE: 2.9 \n  Fold 11 / 22 - District 1 - MAE: 2.69 \n  Fold 12 / 22 - District 12 - MAE: 3.11 \n  Fold 13 / 22 - District 15 - MAE: 2.36 \n  Fold 14 / 22 - District 11 - MAE: 3.29 \n  Fold 15 / 22 - District 18 - MAE: 2.8 \n  Fold 16 / 22 - District 25 - MAE: 2.74 \n  Fold 17 / 22 - District 14 - MAE: 2.75 \n  Fold 18 / 22 - District 19 - MAE: 2.02 \n  Fold 19 / 22 - District 16 - MAE: 2.81 \n  Fold 20 / 22 - District 17 - MAE: 2 \n  Fold 21 / 22 - District 20 - MAE: 2.51 \n  Fold 22 / 22 - District 24 - MAE: 2.19 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Overall results\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 2.81 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 3.8 \n```\n\n\n:::\n:::\n\n\nMean MAE of 2.81 Mean RMSE of 3.8\n\nWe have our cross validation results, here we'll put them in a table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show results\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>LOGO CV Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 5.59 </td>\n   <td style=\"text-align:right;\"> 7.90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 4.03 </td>\n   <td style=\"text-align:right;\"> 6.01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 3.31 </td>\n   <td style=\"text-align:right;\"> 4.24 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 3.29 </td>\n   <td style=\"text-align:right;\"> 4.16 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:right;\"> 3.11 </td>\n   <td style=\"text-align:right;\"> 4.43 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 2.90 </td>\n   <td style=\"text-align:right;\"> 3.80 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 2.87 </td>\n   <td style=\"text-align:right;\"> 3.90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 2.86 </td>\n   <td style=\"text-align:right;\"> 3.76 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 129 </td>\n   <td style=\"text-align:right;\"> 2.81 </td>\n   <td style=\"text-align:right;\"> 3.29 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 2.80 </td>\n   <td style=\"text-align:right;\"> 4.21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 2.75 </td>\n   <td style=\"text-align:right;\"> 4.09 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 2.74 </td>\n   <td style=\"text-align:right;\"> 3.89 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 2.69 </td>\n   <td style=\"text-align:right;\"> 3.43 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 112 </td>\n   <td style=\"text-align:right;\"> 2.66 </td>\n   <td style=\"text-align:right;\"> 3.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 2.51 </td>\n   <td style=\"text-align:right;\"> 3.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 2.36 </td>\n   <td style=\"text-align:right;\"> 3.14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 235 </td>\n   <td style=\"text-align:right;\"> 2.21 </td>\n   <td style=\"text-align:right;\"> 3.93 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:right;\"> 2.19 </td>\n   <td style=\"text-align:right;\"> 2.75 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 2.02 </td>\n   <td style=\"text-align:right;\"> 2.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 107 </td>\n   <td style=\"text-align:right;\"> 2.02 </td>\n   <td style=\"text-align:right;\"> 2.63 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 2.00 </td>\n   <td style=\"text-align:right;\"> 2.43 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 2.00 </td>\n   <td style=\"text-align:right;\"> 2.78 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nOur MAE and RMSE varies across test districts, ranging from 2.00 to 5.59 for the MAE, and 2.43 to 7.90 for the RMSE.\n\n#### Part 6: Model Evaluation\n\n-   Compare to KDE baseline\n\nNow, we've created a model using negative binomial regression that we can use to predict burglaries in Chicago. Let's go ahead and compare it to the KDE baseline we created back in step\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit final model on all data\nfinal_model <- glm.nb(\n  countBurglaries ~ countPotholes + potholes.nn + countLightsOut + \n    dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Add predictions back to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model, type = \"response\")[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\n# Also add KDE predictions (normalize to same scale as counts)\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n```\n:::\n\n\nNow that we have our final model, let's compare it to our KDE baseline map from Step 2, Part 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We'll make three maps: one of burglary counts in Chicago, one of the predicted counts from the negative binomial regression model, and one from the KDE baseline map predictions.\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (Neg. Binomial)\") +\n  theme_crime()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_crime()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThe negative binomial regression model's predictions look more similar to actual burglaries than the KDE baseline predictions do. The model's predictions capture the sharper differences of burglaries across cells, whereas the KDE baseline's map has a more vague, less precise estimation of burglary counts by cell. The KDE baseline, at least visually, does a better job at capturing general areas of high burglary counts than the model does.\n\nTo get a better idea of how the model performs compared to the KDE estimate, we'll run some calculations in R to get statistical model performance measures (MAE and RMSE) and put them into a table for easy comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 2.58 </td>\n   <td style=\"text-align:right;\"> 3.73 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 2.06 </td>\n   <td style=\"text-align:right;\"> 2.95 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nOur model's mean absolute error (MAE) and root mean square error (RMSE) were both higher than the kde baseline's. A higher MAE and RMSE means the model does a poorer job of predicting burglaries than the kde map.\n\n## Step 3: Write Your Analysis\n\n### What we did\n\nThroughout the exercise, I left comments and explanations for what visuals and outputs represent, and why we do each step.\n\nIn Part 1 of this analysis, we loaded Chicago 311 violation data and spatial features and visualized our data to show spatial patterns of potholes and burglaries in the city. In Part 2, we created a fishnet grid and aggregated our data to the grid cells, creating a sort of raster overlay for the city. In Part 3, we calculated spatial features such as k-nearest neighbors and distance to hot spots which we obtained by performing a Local Moran's I analysis. We also loaded in street light outages as an additional predictor. In Part 4, we ran a Poisson regression using our predictors (including the spatial features created in part 3), we then ran a Negative Binomial regression which better addressed our data's wide dispersion, and compared the two models. In Part 5, we implemented a LOGO cross validation to assess our model's performance in predicting burglary values using our Negative Binomial model. And finally in part 6, we compared our Negative Binomial model's predictive ability to our initial KDE density baseline from Part 3 and found that our model's predictive ability is worse than just using a kernel density map to predict where burglaries will occur.\n\n### What we found\n\nIn the end, the Negative Binomial model was stronger than the Poisson model, but still under-performed compared to just using a KDE prediction. In the future, to achieve a better predictive model, I would search for more spatial or demographic data that may help to define the characteristics of each 500x500m cell we predicted on. One major issue with the 311 dataset (The potholes and light outage data) is that the rate at which people report violations may vary greatly across neighborhoods. For instance, in a neighborhood where potholes are very common, one would probably be less likely to report a small pothole on a quiet street. On the other hand, in a neighborhood where potholes are less common, one would be far more likely to report a small pothole they come across. By including other data that helps to describe characteristics of a grid cell, the bias in the 311 dataset would have far less of an effect on the overall predictive ability of the model.\n",
    "supporting": [
      "lab_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}